apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "client-chart.fullname" . }}
  labels:
    app: {{ include "client-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "client-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "client-chart.name" . }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
