replicaCount: 2
image:
  repository: saharletaief23/proservice
  tag: tickets-service
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
env:
  MONGO_URI: "mongodb://ticket-mongo-service:27017/tickets"
  JWT_SECRET_NAME: "jwt-secret"
  JWT_KEY: "JWT_KEY"
  RABBITMQ_URL: "amqp://ticketuser:user@rabbit-service.default.svc.cluster.local:5672"
imagePullSecrets:
  - name: docker-cred
